### ISSUE TITLE
消费者减完后，还可以正常接收请求吗？

### ISSUE THREAD

**Issue by allon2** [Rookiexu/disruptorDynamicConsumer#1]
消费者减完后，还可以正常接收请求吗？我做了一下减消费者，发现无法正常接收消费者

**Comment by Rookiexu** [comment]
减消费者会丢掉一个消息,但是还是可以继续接收消费者的....丢消息的问题,我向disruptor提交了一个pr,你可以看一下

**Comment by Rookiexu** [comment]
丢消息的部分,我在自己项目里面是改了disruptor源码重新编译出了一个jar包来用的

**Comment by allon2** [comment]
我现在是减消费者后，请求的消息无法进入队列中，更糟糕

**Comment by allon2** [comment]
丢消息部分的代码可以分享一下吗？

**Comment by Rookiexu** [comment]
https://github.com/LMAX-Exchange/disruptor/pull/287/files   这是提交的pr....你是自己的项目出了问题还是我的示例出了问题呢?

**Comment by allon2** [comment]
不知道哦，我按照你这个做了一个简单的


`  WorkProcessor<MessageEvent> tprocessor= processorList.get(0);

        tprocessor.halt();

        ringBuffer.removeGatingSequence(tprocessor.getSequence());`
基本也就是这样的

**Comment by allon2** [comment]
写减消费者的时候还有其他需要注意的地方吗？

**Comment by Rookiexu** [comment]
你的队列长度是多少,减了多少消费者呢

**Comment by allon2** [comment]
队列长度是1024，测试的时候，消费者是从10个减到1个

**Comment by Rookiexu** [comment]
需要修改disruptor的代码,参考我的pr https://github.com/LMAX-Exchange/disruptor/pull/287
