### ISSUE TITLE
依赖事件也可以动态增加吗？

### ISSUE THREAD

**Issue by dukeduke2002** [Rookiexu/disruptorDynamicConsumer#2]
请教一个问题，假如消费者是菱形关系，a，b并发后执行c。那么对于c而言也能动态增加吗？

**Comment by Rookiexu** [comment]
disruptor本身在功能上是可以实现的,但是没有封装,另外我这个项目里面也没有去实现

**Comment by Rookiexu** [comment]
等一下哈,ab并发之后c..是什么意思

**Comment by dukeduke2002** [comment]
就是DSL的功能，handleEventWith(A, B).then(C)的时候。C能动态增加吗？

**Comment by dukeduke2002** [comment]
我测试了WorkerPool如下（Hander1执行完后执行Handler2）

1. 代码如下

```java
    EventHandlerGroup<Trade> handlerGroup = disruptor.handleEventsWithWorkerPool(new Handler1("1"), new Handler1("2"));  
    handlerGroup.thenHandleEventsWithWorkerPool(new Handler2(), new Handler2());
```

2. 然后在Handler1中模拟了某些操作比较慢的情况

```java
public class Handler1 implements EventHandler<Trade>, WorkHandler<Trade> {
    private String num;
    public Handler1(String num) {
        this.num = num;
    }
    @Override public void onEvent(Trade event) throws Exception {
        event.setName("h" + num);
        if ("1".equals(num)) { //**假如num为1那么sleep 50秒。假如不为1，那么处理能很快完成**。
            Thread.sleep(50000);
        }
    }
}
```

3. 接着我发布了2个事件
```java
ringBuffer.publishEvent(tradeTransloator); 
ringBuffer.publishEvent(tradeTransloator);
``` 

执行后发现比如2个事件都被Handler1都执行结束后，才会执行Handler2。。。。。

我们能不能实现：因为Handler1("2")执行比较快，所以Handler2先执行Handler1("2)的结果，而不必等待Handler1("1")？

我个人理解因为存在Barrier，所以Handler2需要等待Handler1的处理**都**执行完成后，才能开始自己的处理(waitStrategy.waitFor方法)。这个是disruptor的限制吗？

**Comment by Rookiexu** [comment]
貌似不行...workWithPool这种模式我之前知乎写了源码解析 [源码解析](https://zhuanlan.zhihu.com/p/100724907),你可以看一下,我先简单说一下它的模式,就是先取队列的一个位置,当队列位置有数据的时候就去处理,因为是环形队列,队列追尾的时候就只有等了...所以如果有一个handler卡死了,是可能导致其他的handler都等着的

**Comment by dukeduke2002** [comment]
嗯。我也看源码了，FixedSequenceGroup里面是取最小的sequence。WorkerPool的时候，sequences里面保存了WorkerPool的workSequence和WorkProcessor的sequence(也就是Handler1("1")和Handler1("2)相对应的sequence),假如Handler1("1")不处理完，那么永远Handler2的处理启动不起来。。
```java
    public long get()
    {
        return Util.getMinimumSequence(sequences);
    }
```

**Comment by dukeduke2002** [comment]
那这样的话Disruptor没发在高并发/高可用的业务场景下，执行带依赖关系的事件都卡死的话，那谁受的了。。。

**Comment by Rookiexu** [comment]
讲道理,你不应该有阻塞啊...有阻塞怎么可能高并发的起来

**Comment by Rookiexu** [comment]
改异步的操作异步化,依赖关系事件的处理方式是同步的思想,同步本来就不会太高并发

**Comment by dukeduke2002** [comment]
举个例子呀。比如说Handler1里面的处理如下：
```java
if (条件A) {
   RPC调用
} else if (条件B) {
   简单的变量设置操作
}
```
这个时候过来100个事件，第一个事件符合条件A，其他的99个事件符合条件B。因为第一个事件符合条件A，所以剩余的99个事件都得等着第一个事件处理完，才能进行Handler2的处理。
一般RPC调用我们都有timeout处理，比如说100毫秒，那也是其他的99个事件需要等待100毫秒。。。。这不科学呀。。

**Comment by Rookiexu** [comment]
你disruptor长度多少啊,这种不会啊,得99个全部执行完了,如果你第一个还挂着,才会卡主啊

**Comment by dukeduke2002** [comment]
嗯。因为条件B的执行非常快，而条件A的RPC执行的慢。。。所以99个事件执行完后，RPC还没有调用完的可能性极其高呢。

**Comment by dukeduke2002** [comment]
对ProcessingSequenceBarrier的waitFor方法进行改写，WorkPool模式下，只要有1个Handler1执行完了，Handler2就接手处理应该更合理。不过这就和迈克尔起的变量名Barrier（屏障）冲突了吧。。。

**Comment by Rookiexu** [comment]
我现在才明白你说的情况,关键在于你跳着处理的话,事件很容易漏掉或者重复消费了啊,不然就要很麻烦的维护处理状态,性能就下去了

**Comment by dukeduke2002** [comment]
我重新看了disruptor官网中对自己的定义：A High Performance Inter-Thread Messaging Library。
处理这种DSL关系应该它还是不擅长？？？

**Comment by dukeduke2002** [comment]
我在官网里面提了一个问题：[Can parallelly process different eventHandler type when using workerPool #294](https://github.com/LMAX-Exchange/disruptor/issues/294)

**Comment by Rookiexu** [comment]
应该是这么理解吧,比如netty,如果你在netty的io线程读完消息直接进行业务处理,你的rpc会卡住当前线程所有玩家,但是不能因为这个说netty不是高性能的..disruptor在这一点上其实跟netty是类似的

**Comment by Rookiexu** [comment]
如果你没有有阻塞操作,直接在disruptor处理就可以了,如果有的话,还是之前提到的,该异步的异步化

**Comment by dukeduke2002** [comment]
是的。跟你说的一样，这是治根的方法。
