### ISSUE TITLE
支持future模式？

### ISSUE THREAD

**Issue by dukeduke2002** [Rookiexu/disruptorDynamicConsumer#3]
还有一个问题，disruptor现在不支持future模式。假如我publish了一个event，我怎么在发布端得到消费者执行后的结果？

**Comment by Rookiexu** [comment]
你可以在event里面放一个future对象,然后在业务handler后面跟一个handler去触发这个future,就可以了

**Comment by dukeduke2002** [comment]
那这样还是在消费端得到结果？能不能做到**Future futures =** ringBuffer.publishEvent(tradeTransloator)。这样我们就可以在事件发布方得到处理结果了。
